// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetFeederWebApi.Data;

#nullable disable

namespace PetFeederWebApi.Migrations
{
    [DbContext(typeof(PetFeederContext))]
    [Migration("20260115185455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetFeederWebApi.Models.Aktivacija", b =>
                {
                    b.Property<int>("AktivacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AktivacijaID"));

                    b.Property<int>("UredjajID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("AktivacijaID");

                    b.HasIndex("UredjajID");

                    b.ToTable("Aktivacije");
                });

            modelBuilder.Entity("PetFeederWebApi.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("PetFeederWebApi.Models.KorisnikUredjaj", b =>
                {
                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("UredjajID")
                        .HasColumnType("int");

                    b.HasKey("KorisnikID", "UredjajID");

                    b.HasIndex("UredjajID");

                    b.ToTable("KorisniciUredjaji");
                });

            modelBuilder.Entity("PetFeederWebApi.Models.Uredjaj", b =>
                {
                    b.Property<int>("UredjajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UredjajID"));

                    b.Property<DateTime?>("ImaoObrokVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Izbacivanja")
                        .HasColumnType("int");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PosljednjiUpdateVrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("UredjajID");

                    b.ToTable("Uredjaji");
                });

            modelBuilder.Entity("PetFeederWebApi.Models.Aktivacija", b =>
                {
                    b.HasOne("PetFeederWebApi.Models.Uredjaj", "Uredjaj")
                        .WithMany()
                        .HasForeignKey("UredjajID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uredjaj");
                });

            modelBuilder.Entity("PetFeederWebApi.Models.KorisnikUredjaj", b =>
                {
                    b.HasOne("PetFeederWebApi.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetFeederWebApi.Models.Uredjaj", "Uredjaj")
                        .WithMany()
                        .HasForeignKey("UredjajID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uredjaj");
                });
#pragma warning restore 612, 618
        }
    }
}
